var = {'ok': True, 'result': [{'update_id': 881346994, 'message': {'message_id': 2122,
                                                                   'from': {'id': 557099145, 'is_bot': False,
                                                                            'first_name': 'Tessa',
                                                                            'username': 'tessa_z',
                                                                            'language_code': 'en'},
                                                                   'chat': {'id': 557099145, 'first_name': 'Tessa',
                                                                            'username': 'tessa_z', 'type': 'private'},
                                                                   'date': 1589543234,
                                                                   'reply_to_message': {'message_id': 2121,
                                                                                        'from': {'id': 967526375,
                                                                                                 'is_bot': True,
                                                                                                 'first_name': 'R◡̈AOK bot',
                                                                                                 'username': 'RUAOK_bot'},
                                                                                        'chat': {'id': 557099145,
                                                                                                 'first_name': 'Tessa',
                                                                                                 'username': 'tessa_z',
                                                                                                 'type': 'private'},
                                                                                        'date': 1589543214,
                                                                                        'text': 'Which post would you like to check? Please give me the post number indicated at the top of the post.'},
                                                                   'text': 'Unknown'}}]}